export const WISH_CREATE_REQUEST = 'WISH_CREATE_REQUEST'
export const WISH_CREATE_SUCCESS = 'WISH_CREATE_SUCCESS'
export const WISH_CREATE_FAIL = 'WISH_CREATE_FAIL'
export const WISH_CREATE_RESET = 'WISH_CREATE_RESET'
